#Instruccion para crear el contenedor
#Despues de configurar las instrucciones del contenedor
#escribir el comando en la terminal y dentro del proyecto donde este el archivo docker-compose.yml (docker compose up) para levantar el contenedor
version: '3.1'
services:
  ventsoft:
    image: ventsoft
    container_name: vent-soft
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - ventsoft-network
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5433/ventsoft
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  db:
    image: postgres:16.1-alpine3.18
    container_name: ventsoft-db
    volumes:
      - my-db:/var/lib/postgresql/data
    restart: always
    ports:
      - '5433:5432'
    networks:
      - ventsoft-network
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ventsoft'

networks:
  ventsoft-network:

volumes:
  my-db: